services:
  bitcoind:
    container_name: bitcoind
    build: https://github.com/mu373/docker-bitcoind-image.git
    # build:
    #   context: ../docker-bitcoind-image
    #   dockerfile: Dockerfile
    image: mu373/docker-bitcoind
    volumes:
      - ./bitcoind-data:/bitcoin/.bitcoin #This is where the blockchain will be saved. Requires approximately 580GB as of August 2023. You can use external drives too! (e.g. /mnt/disk1/bitcoind)
      - ./bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
      - ./torrc.d/:/etc/torrc.d/
    ports:
      # - 8333:8333
      - 8332:8332 #RPC
    restart: always

networks:
  default:
    name: bitcoin-nw
    driver: bridge
